server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 1000GB
      max-request-size: 1000GB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teee3
    username: root
    password: Root_123456